# Generated by Django 4.2.14 on 2024-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='best_before',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='use_by',
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_date_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Best-before-date'), (1, 'Use-by-date')], null=True),
        ),
    ]
